version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 18
        commands:
            - echo Installing dependencies...
            - npm install

    pre_build:
        commands:
            - echo Running pre-build actions...

    build:
        commands:
            - echo Build started on `date`
            - npm run build

    post_build:
        commands:
            - echo Build completed on `date`
            - echo Uploading build artifacts to S3 in us-east-1...
            - aws s3 sync build/ s3://taskcurator.com/ --delete
            - echo "Invalidating CloudFront cache for taskcurator.com"
            - aws cloudfront create-invalidation --distribution-id E2BBB0QKJF2QFK --paths "/*"
            - echo "Invalidating CloudFront cache for www.taskcurator.com"
            - aws cloudfront create-invalidation --distribution-id ET847UKS4I1TM --paths "/*"

cache:
    paths:
        - "node_modules/**/*"
